version: '3.7'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits: 
      memlock:
        soft: -1 
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add: 
      - IPC_LOCK
    volumes:
      - "/home/vagrant/volumes/elk:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk-network

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash-oss:${ELK_VERSION}
    restart: unless-stopped
    volumes:
      - /home/vagrant/volumes/elk/logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTICSEARCH_HOST: http://localhost:9200
      ELASTICSEARCH_PORT: 9200
    networks:
      - elk-network
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    restart: unless-stopped
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://localhost:9200
    volumes:
      - /home/vagrant/volumes/elk/kibana/config:/opt/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk-network
    depends_on:
      - elasticsearch

networks:
  elk-network:
    driver: bridge