version: '3.7'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elasticsearch
    restart: unless-stopped
    command: 'mkdir -p /usr/share/elasticsearch/config/certs/'
    environment:
      discovery.type: single-node
      xpack.license.self_generated.type: basic
      xpack.monitoring.collection.enabled: true
      xpack.security.enabled: false
      #xpack.security.transport.ssl.enabled: true
      #xpack.security.transport.ssl.verification_mode: certificate 
      #xpack.security.transport.ssl.client_authentication: required
      #xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elastic-stack-ca.p12
      #xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elastic-stack-ca.p12
      LS_JAVA_OPTS: '-Xm1g -Xms1g'
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      KIBANA_PASSWORD: ${KIBANA_PASSWORD}
      STACK_VERSION: ${STACK_VERSION}
      ELASTICSEARCH_PORT: ${ES_PORT}
      KIBANA_PORT: ${KIBANA_PORT}
    volumes:
      - /home/vagrant/volumes/elk/elastic/certs:/usr/share/elasticsearch/data
    ulimits: 
      memlock:
        soft: -1 
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add: 
      - IPC_LOCK
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elk-network

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash-oss:${STACK_VERSION}
    restart: unless-stopped
    environment:
      LS_JAVA_OPTS: '-Xmx256m -Xms256m'
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD}
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
      ELASTICSEARCH_PORT: ${ES_PORT}
    volumes:
      - /home/vagrant/volumes/elk/logstash/conf.d:/etc/logstash/conf.d
    ports:
      - '5000:5000'
      - '5044:5044'
      - '9600:9600'
    networks:
      - elk-network
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    restart: unless-stopped
    environment:
      SERVER_NAME: kibana
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HOSTS}
      KIBANA_USERNAME: ${KIBANA_USERNAME}
      KIBANA_PASSWORD: ${KIBANA_PASSWORD}
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: ${XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD}
    ports:
      - '5601:5601'
    networks:
      - elk-network
    depends_on:
      - elasticsearch

networks:
  elk-network:
    driver: bridge