# ============================== Filebeat inputs ===============================

filebeat.inputs:

- type: filestream
  id: srv01-logs
  enabled: true
  paths:
    - /var/log/*.log
  exclude_lines: ['sit']

# ============================== Filebeat modules ==============================

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# ======================= Elasticsearch template setting =======================

setup.template.enabled: true
setup.template.name: "filebeat-%{[agent.version]}-${HOSTNAME}-template"
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0
  index.codec: best_compression

# ====================== Index Lifecycle Management (ILM) ======================

setup.ilm.enabled: true
setup.ilm.overwrite: false
setup.ilm.policy_name: "filebeat-%{[agent.version]}-${HOSTNAME}-policy"
setup.ilm.rollover_alias: "filebeat-%{[agent.version]}-${HOSTNAME}"
setup.ilm.pattern: "000001"

# =================================== Kibana ===================================

setup.kibana:

# ================================== Outputs ===================================

output.elasticsearch:

  hosts: ["IP:9200"]
    
# ================================= Processors =================================

processors:

  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

  - drop_fields:
      fields: ["host.os.codename","host.os.family","host.os.kernel","host.os.platform","host.os.type","host.os.name","host.os.version","input.type"]